name: Docker Image CI

on:
  push:
    branches: [ "malformed-requirements.txt" ]
  pull_request:
    branches: [ "malformed-requirements.txt" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag aliponneth/django:v1
      #run: docker build -t container_tag --build-arg MYAPP_IMAGE=aliponneth/flask-api-demo .
      
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: aliponneth/django
        tags: container_tag --build-arg MYAPP_IMAGE=aliponneth/flask-api-demo   #v1, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
